name: Deploy playground

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Fetch submodule
      run: git submodule update --init --recursive
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Build
      run: |
        npm install
        npm run build
        mv dist/polyfill.js
        curl -o playground/bootstrap.css https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.css
        curl -o playground/bootstrap.js https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.js

    - name: Deploy to Netlify
      uses: netlify/actions/cli@master
      with:
        args: deploy --dir=playground --prod
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}